# ./.github/workflows/add_issues_to_oberocks_project.yml

name: Add issues to @oberocks project

on:
  issues:
    types:
      - opened
      - transferred
      # - labeled


jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/oberocks/projects/11
          github-token: ${{ secrets.MATT_MCT_LLC_AUTOMATION_PERSONAL_ACCESS_TOKEN }}